class YoloConfig {
  static const String modelPath = "assets/indoor_objects_model.tflite";
  static const String labelsPath = "assets/labels.txt";
  static const double confidenceThreshold = 0.55;
  static const double iouThreshold = 0.4;
  
  // 53 classes from labels.txt
  static const List<Map<String, dynamic>> yoloClasses = [
    {'tag': 'backpack', 'label': 'backpack'},
    {'tag': 'ball', 'label': 'ball'},
    {'tag': 'bed', 'label': 'bed'},
    {'tag': 'bench', 'label': 'bench'},
    {'tag': 'blackboard', 'label': 'blackboard'},
    {'tag': 'book', 'label': 'book'},
    {'tag': 'cabinet', 'label': 'cabinet'},
    {'tag': 'cabinet_door', 'label': 'cabinet_door'},
    {'tag': 'chair', 'label': 'chair'},
    {'tag': 'clock', 'label': 'clock'},
    {'tag': 'couch', 'label': 'couch'},
    {'tag': 'desk', 'label': 'desk'},
    {'tag': 'door', 'label': 'door'},
    {'tag': 'door_handle', 'label': 'door_handle'},
    {'tag': 'doorknob', 'label': 'doorknob'},
    {'tag': 'doormat', 'label': 'doormat'},
    {'tag': 'drone', 'label': 'drone'},
    {'tag': 'earmuff', 'label': 'earmuff'},
    {'tag': 'eraser', 'label': 'eraser'},
    {'tag': 'game_console', 'label': 'game_console'},
    {'tag': 'gamepad', 'label': 'gamepad'},
    {'tag': 'glass_door', 'label': 'glass_door'},
    {'tag': 'headphone', 'label': 'headphone'},
    {'tag': 'keyboard', 'label': 'keyboard'},
    {'tag': 'laptop', 'label': 'laptop'},
    {'tag': 'microphone', 'label': 'microphone'},
    {'tag': 'microwave', 'label': 'microwave'},
    {'tag': 'mouse', 'label': 'mouse'},
    {'tag': 'open_door', 'label': 'open_door'},
    {'tag': 'oven', 'label': 'oven'},
    {'tag': 'person', 'label': 'person'},
    {'tag': 'pole', 'label': 'pole'},
    {'tag': 'projector', 'label': 'projector'},
    {'tag': 'refrigerator', 'label': 'refrigerator'},
    {'tag': 'refrigerator_door', 'label': 'refrigerator_door'},
    {'tag': 'sharpener', 'label': 'sharpener'},
    {'tag': 'shelf', 'label': 'shelf'},
    {'tag': 'sink', 'label': 'sink'},
    {'tag': 'sliding_door', 'label': 'sliding_door'},
    {'tag': 'speaker', 'label': 'speaker'},
    {'tag': 'statue', 'label': 'statue'},
    {'tag': 'sunglasses', 'label': 'sunglasses'},
    {'tag': 'table', 'label': 'table'},
    {'tag': 'trash_bin', 'label': 'trash_bin'},
    {'tag': 'tripod', 'label': 'tripod'},
    {'tag': 'tv', 'label': 'tv'},
    {'tag': 'vitamin_bottle', 'label': 'vitamin_bottle'},
    {'tag': 'watch', 'label': 'watch'},
    {'tag': 'water_bottle', 'label': 'water_bottle'},
    {'tag': 'webcam', 'label': 'webcam'},
    {'tag': 'whiteboard', 'label': 'whiteboard'},
    {'tag': 'window', 'label': 'window'},
  ];
}
